# Site settings
title: Shreyas Iyer's DevBlog
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "http://l0ftywhizz.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Shreyas Iyer
user_description: I like to play games, and also make them! Currently pursuing Integrated M.Tech in Computer Science an Engineering at International Institute of Information Technology, Bangalore (Batch of 2020).
user_title: Game Developer
email: shreyasiyer14@anon.com
twitter_username: shreyasiyer14
github_username:  l0ftyWhizZ
gplus_username:  shreyasiyer14

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
